// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Models.AbsenceReasons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("AbsenceReasons");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.AttendanceTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceTypes");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Competences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("Department_Id");

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.EmployeeTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Employee_Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Department_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employee_Departments");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Join_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Grades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Outcomes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Pictures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.RequestExits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ExitTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("RequestExits");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name_Of_Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("Department_Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentAbsents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsenceReasonId")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Class_Id")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<string>("CustomReasonDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentClassSectionYear_Section_id")
                        .HasColumnType("int");

                    b.Property<int>("StudentClassSectionYear_Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("StudentClassSectionYear_Working_Year_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceReasonId");

                    b.HasIndex("AttendanceTypeId");

                    b.HasIndex("Class_Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("StudentClassSectionYear_Student_Id", "StudentClassSectionYear_Working_Year_Id", "StudentClassSectionYear_Section_id");

                    b.ToTable("StudentAbsents");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentAttendances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Class_Id")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<string>("CustomReasonDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentClassSectionYear_Section_id")
                        .HasColumnType("int");

                    b.Property<int>("StudentClassSectionYear_Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("StudentClassSectionYear_Working_Year_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceTypeId");

                    b.HasIndex("Class_Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("StudentClassSectionYear_Student_Id", "StudentClassSectionYear_Working_Year_Id", "StudentClassSectionYear_Section_id");

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentGrades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Working_Year_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("Working_Year_Id");

                    b.ToTable("StudentGrades");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student_Class_Section_Year", b =>
                {
                    b.Property<int>("Student_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Working_Year_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Section_id")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int?>("Class_Id")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Student_Id", "Working_Year_Id", "Section_id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("CreatedBy_Id");

                    b.HasIndex("Section_id");

                    b.HasIndex("Working_Year_Id");

                    b.ToTable("Student_Class_Section_Years");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassesId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Date_of_birth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Jop_of_Father")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jop_of_Mother")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Natrual_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number_Father")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number_Mother")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture_Profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birth_Certificate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassesId");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.TaskEvaluations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OutcomeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OutcomeId");

                    b.HasIndex("StudentId");

                    b.ToTable("TaskEvaluations");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Working_Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy_Id");

                    b.ToTable("Working_Years");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.AbsenceReasons", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedAbsenceReasons")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Classes", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedClasses")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Competences", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedCompetences")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Department", "Department")
                        .WithMany("Competences")
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Department", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedDepartments")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Employee_Department", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Department", "Department")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Employees", "User")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Employees", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedEmployees")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentManagementSystem.Models.EmployeeTypes", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Grades", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedGrades")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Outcomes", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Competences", "Competence")
                        .WithMany("Outcomes")
                        .HasForeignKey("CompId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Pictures", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedPictures")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentManagementSystem.Models.Students", "Student")
                        .WithMany("Pictures")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.TaskEvaluations", "Task")
                        .WithMany("Pictures")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.RequestExits", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.StudentAttendances", "Attendance")
                        .WithMany("RequestExits")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedRequestExits")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Section", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedSections")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentAbsents", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.AbsenceReasons", "AbsenceReason")
                        .WithMany("StudentAbsents")
                        .HasForeignKey("AbsenceReasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.AttendanceTypes", "AttendanceType")
                        .WithMany("StudentAbsents")
                        .HasForeignKey("AttendanceTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedStudentAbsents")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Student_Class_Section_Year", "StudentClassSectionYear")
                        .WithMany("StudentAbsents")
                        .HasForeignKey("StudentClassSectionYear_Student_Id", "StudentClassSectionYear_Working_Year_Id", "StudentClassSectionYear_Section_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AbsenceReason");

                    b.Navigation("AttendanceType");

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("StudentClassSectionYear");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentAttendances", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.AttendanceTypes", "AttendanceType")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("AttendanceTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedStudentAttendances")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Student_Class_Section_Year", "StudentClassSectionYear")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("StudentClassSectionYear_Student_Id", "StudentClassSectionYear_Working_Year_Id", "StudentClassSectionYear_Section_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AttendanceType");

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("StudentClassSectionYear");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentGrades", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Grades", "Grade")
                        .WithMany("StudentGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Students", "Student")
                        .WithMany("StudentGrades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Working_Year", "WorkingYear")
                        .WithMany("StudentGrades")
                        .HasForeignKey("Working_Year_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Student");

                    b.Navigation("WorkingYear");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student_Class_Section_Year", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Classes", "Class")
                        .WithMany("StudentClassSectionYears")
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedStudentClassSectionYears")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Section", "Section")
                        .WithMany("StudentClassSectionYears")
                        .HasForeignKey("Section_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Students", "Student")
                        .WithMany("StudentClassSectionYears")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Working_Year", "WorkingYear")
                        .WithMany("StudentClassSectionYears")
                        .HasForeignKey("Working_Year_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("Section");

                    b.Navigation("Student");

                    b.Navigation("WorkingYear");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Students", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Classes", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassesId");

                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedStudents")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.TaskEvaluations", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Outcomes", "Outcome")
                        .WithMany("TaskEvaluations")
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Students", "Student")
                        .WithMany("TaskEvaluations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Outcome");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Working_Year", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Employees", "CreatedBy")
                        .WithMany("CreatedWorkingYears")
                        .HasForeignKey("CreatedBy_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.AbsenceReasons", b =>
                {
                    b.Navigation("StudentAbsents");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.AttendanceTypes", b =>
                {
                    b.Navigation("StudentAbsents");

                    b.Navigation("StudentAttendances");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Classes", b =>
                {
                    b.Navigation("StudentClassSectionYears");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Competences", b =>
                {
                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("EmployeeDepartments");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.EmployeeTypes", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Employees", b =>
                {
                    b.Navigation("CreatedAbsenceReasons");

                    b.Navigation("CreatedClasses");

                    b.Navigation("CreatedCompetences");

                    b.Navigation("CreatedDepartments");

                    b.Navigation("CreatedEmployees");

                    b.Navigation("CreatedGrades");

                    b.Navigation("CreatedPictures");

                    b.Navigation("CreatedRequestExits");

                    b.Navigation("CreatedSections");

                    b.Navigation("CreatedStudentAbsents");

                    b.Navigation("CreatedStudentAttendances");

                    b.Navigation("CreatedStudentClassSectionYears");

                    b.Navigation("CreatedStudents");

                    b.Navigation("CreatedWorkingYears");

                    b.Navigation("EmployeeDepartments");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Grades", b =>
                {
                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Outcomes", b =>
                {
                    b.Navigation("TaskEvaluations");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Section", b =>
                {
                    b.Navigation("StudentClassSectionYears");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentAttendances", b =>
                {
                    b.Navigation("RequestExits");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student_Class_Section_Year", b =>
                {
                    b.Navigation("StudentAbsents");

                    b.Navigation("StudentAttendances");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Students", b =>
                {
                    b.Navigation("Pictures");

                    b.Navigation("StudentClassSectionYears");

                    b.Navigation("StudentGrades");

                    b.Navigation("TaskEvaluations");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.TaskEvaluations", b =>
                {
                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Working_Year", b =>
                {
                    b.Navigation("StudentClassSectionYears");

                    b.Navigation("StudentGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
